# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(max_length=10, null=True, verbose_name='种类')),
                ('abstract', models.CharField(default='文章暂无简介', max_length=255, verbose_name='摘要')),
                ('image', models.ImageField(null=True, upload_to='upload', verbose_name='图片')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创始时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
