# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30, unique=True, verbose_name='英雄名称')),
                ('h_dir', models.TextField(default='暂无', verbose_name='英雄描述')),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='HeroCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.IntegerField(choices=[(1, '战士'), (2, '法师'), (3, '射手'), (4, '刺客'), (5, '坦克'), (6, '辅助')], help_text='类目级别', verbose_name='类目级别')),
            ],
            options={
                'db_table': 'hero_category',
            },
        ),
        migrations.CreateModel(
            name='HeroCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=128, verbose_name='连招名')),
                ('c_dir', models.TextField(default='暂无', verbose_name='连招描述')),
                ('c_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero', verbose_name='英雄')),
            ],
            options={
                'db_table': 'hero_combo',
            },
        ),
        migrations.CreateModel(
            name='HeroSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40, verbose_name='技能名')),
                ('s_dir', models.TextField(verbose_name='技能描述')),
                ('s_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero', verbose_name='英雄')),
            ],
            options={
                'db_table': 'hero_skill',
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='h_category',
            field=models.ManyToManyField(null=True, to='hero.HeroCategory', verbose_name='英雄类别'),
        ),
    ]
